#!/bin/bash

# Find out script's dir, resolving any links to the script itself
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR/..
if [[ ! -z `ls src/*.o[0-9] 2> /dev/null` ]]; then rm src/*.o[0-9]; fi
gsc -e '(begin (include "/data/projects/scheme-prelude/src/prelude.scm") (include "compiler.scm"))'
